name:                circuit-breaker
version:             0.1.0.0
github:              "https://github.com/aleryo/one-log"
license:             BSD3
author:              "Arnaud Bailly"
maintainer:          "arnaud@aleryo.com"
copyright:           "2018 Arnaud Bailly"
ghc-options:  -Wall -Werror

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abailly/one-log/log-controller/readme.md>

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- bytestring
- lens
- lens-aeson
- log-controller
- mtl
- optparse-generic
- parsec
- pet-store-backend
- pipes
- pipes-bytestring
- process
- template-haskell
- text

library:
  source-dirs: src
  exposed-modules: OneLog.CircuitBreaker

executables:
  circuit-breaker:
    main:                circuit-breaker.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  circuit-breaker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - circuit-breaker
    - file-embed
    - hspec
    - hspec-discover
